#!/bin/bash
# Lili Peng
# Lab3 - Failed Login Report
# CS3030 - Scripting

# Make sure there is one argument being passed in when calling the script
if [ $# -ne 1 ]
then
echo "Usage: flog LOGFILE"
exit 1
fi

sed -n 's/.*Failed password for \([a-z0-9A_Z_]*\) .*/\1/p' <$1 >s1out

sort <s1out >s2out

uniq -c <s2out >s3out

sort -k1,1nr -k2,2 <s3out >s4out

sed 's/invalid/\&lt;UNKNOWN\&gt;/' <s4out >s5out

# Check to see if s6out already exists
if [ -f s6out ]
then
rm s6out
fi

cat s5out| while read count userid; do
printf "%'d %s\n" "$count" "$userid" >>s6out
done

sed 's|^|<br />|' <s6out >s7out

now=$(date)
sed "1s|^|<html>\n<body><h1>Failed Login Attempts Report as of ${now}</h1>\n|" <s7out >s8out
sed -i '$s|$|</body> </html>|' s8out

# Print out the final output
echo "$(cat s8out)"

exit 0

